// <auto-generated />
namespace DataAccsessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration_addcontentstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_addcontentstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202212081037457_migration_addcontentstatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
